export default class DemoData {
    demo_data() {
        let data =
        {
            requisition_items: [
                {
                    id: 1,
                    title: 'DHK0351',
                    date: '09/12/2020',
                    requisition: 'Requisitions 01',
                    area: 'Cumilla',
                    status: 'Draft',
                    mdcn_name: 'Ansulin® Pen Cartridge',
                    qty: '100 IU/ml',
                    desc: 'Insulin Human (rDNA)',
                    type: 'Paricatamole',
                },
                {
                    id: 2,
                    title: 'DHK0351',
                    date: '09/12/2020',
                    requisition: 'Requisitions 01',
                    area: 'Cumilla',
                    status: 'Pending',
                    mdcn_name: 'Ansulin® Pen Cartridge',
                    qty: '110 IU/ml',
                    desc: 'Insulin Human (rDNA)',
                    type: 'Paricatamole',
                },
                {
                    id: 3,
                    title: 'DHK0371',
                    date: '09/12/2020',
                    requisition: 'Requisitions 01',
                    area: 'Cumilla',
                    status: 'Submited',
                    mdcn_name: 'Ansulin® Pen Cartridge',
                    qty: '120 IU/ml',
                    desc: 'Insulin Human (rDNA)',
                    type: 'Paricatamole',
                },
                {
                    id: 4,
                    title: 'DHK0381',
                    date: '09/12/2020',
                    requisition: 'Requisitions 01',
                    area: 'Cumilla',
                    status: 'Draft',
                    mdcn_name: 'Ansulin® Pen Cartridge',
                    qty: '130 IU/ml',
                    desc: 'Insulin Human (rDNA)',
                    type: 'Paricatamole',
                },
                {
                    id: 5,
                    title: 'DHK0391',
                    date: '09/12/2020',
                    requisition: 'Requisitions 01',
                    area: 'Cumilla',
                    status: 'Pending',
                    mdcn_name: 'Ansulin® Pen Cartridge',
                    qty: '140 IU/ml',
                    desc: 'Insulin Human (rDNA)',
                    type: 'Paricatamole',
                },
                {
                    id: 6,
                    title: 'DHK0302',
                    date: '09/12/2020',
                    requisition: 'Requisitions 01',
                    area: 'Cumilla',
                    status: 'Submited',
                    mdcn_name: 'Ansulin® Pen Cartridge',
                    qty: '150 IU/ml',
                    desc: 'Insulin Human (rDNA)',
                    type: 'Paricatamole',
                },
                {
                    id: 7,
                    title: 'DHK0303',
                    date: '09/12/2020',
                    requisition: 'Requisitions 01',
                    area: 'Cumilla',
                    status: 'Draft',
                    mdcn_name: 'Ansulin® Pen Cartridge',
                    qty: '160 IU/ml',
                    desc: 'Insulin Human (rDNA)',
                    type: 'Paricatamole',
                },
                {
                    id: 8,
                    title: 'DHK0304',
                    date: '09/12/2020',
                    requisition: 'Requisitions 01',
                    area: 'Cumilla',
                    status: 'Pending',
                    mdcn_name: 'Ansulin® Pen Cartridge',
                    qty: '170 IU/ml',
                    desc: 'Insulin Human (rDNA)',
                    type: 'Paricatamole',
                },
                {
                    id: 9,
                    title: 'DHK0305',
                    date: '09/12/2020',
                    requisition: 'Requisitions 01',
                    area: 'Cumilla',
                    status: 'Submited',
                    mdcn_name: 'Ansulin® Pen Cartridge',
                    qty: '180 IU/ml',
                    desc: 'Insulin Human (rDNA)',
                    type: 'Paricatamole',
                },
                {
                    id: 10,
                    title: 'DHK0306',
                    date: '09/12/2020',
                    requisition: 'Requisitions 01',
                    area: 'Cumilla',
                    status: 'Draft',
                    mdcn_name: 'Ansulin® Pen Cartridge',
                    qty: '100 IU/ml',
                    desc: 'Insulin Human (rDNA)',
                    type: 'Paricatamole',
                },
                {
                    id: 11,
                    title: 'DHK0307',
                    date: '09/12/2020',
                    requisition: 'Requisitions 01',
                    area: 'Cumilla',
                    status: 'Pending',
                    mdcn_name: 'Ansulin® Pen Cartridge',
                    qty: '100 IU/ml',
                    desc: 'Insulin Human (rDNA)',
                    type: 'Paricatamole',
                },
                {
                    id: 12,
                    title: 'DHK0301',
                    date: '09/12/2020',
                    requisition: 'Requisitions 01',
                    area: 'Cumilla',
                    status: 'Submited',
                    mdcn_name: 'Ansulin® Pen Cartridge',
                    qty: '100 IU/ml',
                    desc: 'Insulin Human (rDNA)',
                    type: 'Paricatamole',
                },
                {
                    id: 13,
                    title: 'DHK0301',
                    date: '09/12/2020',
                    requisition: 'Requisitions 01',
                    area: 'Cumilla',
                    status: 'Draft',
                    mdcn_name: 'Ansulin® Pen Cartridge',
                    qty: '100 IU/ml',
                    desc: 'Insulin Human (rDNA)',
                    type: 'Paricatamole',
                },
                {
                    id: 14,
                    title: 'DHK0301',
                    date: '09/12/2020',
                    requisition: 'Requisitions 01',
                    area: 'Cumilla',
                    status: 'Pending',
                    mdcn_name: 'Ansulin® Pen Cartridge',
                    qty: '100 IU/ml',
                    desc: 'Insulin Human (rDNA)',
                    type: 'Paricatamole',
                },
                {
                    id: 15,
                    title: 'DHK0301',
                    date: '09/12/2020',
                    requisition: 'Requisitions 01',
                    area: 'Cumilla',
                    status: 'Submited',
                    mdcn_name: 'Ansulin® Pen Cartridge',
                    qty: '100 IU/ml',
                    desc: 'Insulin Human (rDNA)',
                    type: 'Paricatamole',
                },
                {
                    id: 16,
                    title: 'DHK0302',
                    date: '09/12/2020',
                    requisition: 'Requisitions 01',
                    area: 'Cumilla',
                    status: 'Submited',
                    mdcn_name: 'Ansulin® Pen Cartridge',
                    qty: '150 IU/ml',
                    desc: 'Insulin Human (rDNA)',
                    type: 'Paricatamole',
                },
                {
                    id: 17,
                    title: 'DHK0303',
                    date: '09/12/2020',
                    requisition: 'Requisitions 01',
                    area: 'Cumilla',
                    status: 'Draft',
                    mdcn_name: 'Ansulin® Pen Cartridge',
                    qty: '160 IU/ml',
                    desc: 'Insulin Human (rDNA)',
                    type: 'Paricatamole',
                },
                {
                    id: 18,
                    title: 'DHK0304',
                    date: '09/12/2020',
                    requisition: 'Requisitions 01',
                    area: 'Cumilla',
                    status: 'Pending',
                    mdcn_name: 'Ansulin® Pen Cartridge',
                    qty: '170 IU/ml',
                    desc: 'Insulin Human (rDNA)',
                    type: 'Paricatamole',
                },
                {
                    id: 19,
                    title: 'DHK0305',
                    date: '09/12/2020',
                    requisition: 'Requisitions 01',
                    area: 'Cumilla',
                    status: 'Submited',
                    mdcn_name: 'Ansulin® Pen Cartridge',
                    qty: '180 IU/ml',
                    desc: 'Insulin Human (rDNA)',
                    type: 'Paricatamole',
                },
                {
                    id: 20,
                    title: 'DHK0306',
                    date: '09/12/2020',
                    requisition: 'Requisitions 01',
                    area: 'Cumilla',
                    status: 'Draft',
                    mdcn_name: 'Ansulin® Pen Cartridge',
                    qty: '100 IU/ml',
                    desc: 'Insulin Human (rDNA)',
                    type: 'Paricatamole',
                },
                {
                    id: 21,
                    title: 'DHK0307',
                    date: '09/12/2020',
                    requisition: 'Requisitions 01',
                    area: 'Cumilla',
                    status: 'Pending',
                    mdcn_name: 'Ansulin® Pen Cartridge',
                    qty: '100 IU/ml',
                    desc: 'Insulin Human (rDNA)',
                    type: 'Paricatamole',
                },
                {
                    id: 22,
                    title: 'DHK0301',
                    date: '09/12/2020',
                    requisition: 'Requisitions 01',
                    area: 'Cumilla',
                    status: 'Submited',
                    mdcn_name: 'Ansulin® Pen Cartridge',
                    qty: '100 IU/ml',
                    desc: 'Insulin Human (rDNA)',
                    type: 'Paricatamole',
                },
                {
                    id: 23,
                    title: 'DHK0301',
                    date: '09/12/2020',
                    requisition: 'Requisitions 01',
                    area: 'Cumilla',
                    status: 'Draft',
                    mdcn_name: 'Ansulin® Pen Cartridge',
                    qty: '100 IU/ml',
                    desc: 'Insulin Human (rDNA)',
                    type: 'Paricatamole',
                },
                {
                    id: 24,
                    title: 'DHK0301',
                    date: '09/12/2020',
                    requisition: 'Requisitions 01',
                    area: 'Cumilla',
                    status: 'Pending',
                    mdcn_name: 'Ansulin® Pen Cartridge',
                    qty: '100 IU/ml',
                    desc: 'Insulin Human (rDNA)',
                    type: 'Paricatamole',
                },
                {
                    id: 25,
                    title: 'DHK0301',
                    date: '09/12/2020',
                    requisition: 'Requisitions 01',
                    area: 'Cumilla',
                    status: 'Submited',
                    mdcn_name: 'Ansulin® Pen Cartridge',
                    qty: '100 IU/ml',
                    desc: 'Insulin Human (rDNA)',
                    type: 'Paricatamole',
                }
            ],
            create_requisition_items_table_data: [
                {
                    name: 'Ace® Power',
                    qty: '500mg',
                    type: 'Paricatamole',
                },
                {
                    name: 'Ace® Power',
                    qty: '500mg',
                    type: 'Paricatamole',
                },
                {
                    name: 'Ace® Power',
                    qty: '500mg',
                    type: 'Paricatamole',
                },
                {
                    name: 'Ace® Power',
                    qty: '500mg',
                    type: 'Paricatamole',
                },
                {
                    name: 'Ace® Power',
                    qty: '500mg',
                    type: 'Paricatamole',
                },
                {
                    name: 'Ace® Power',
                    qty: '500mg',
                    type: 'Paricatamole',
                },
                {
                    name: 'Ace® Power',
                    qty: '500mg',
                    type: 'Paricatamole',
                },
                {
                    name: 'Ace® Power',
                    qty: '500mg',
                    type: 'Paricatamole',
                },
                {
                    name: 'Ace® Power',
                    qty: '500mg',
                    type: 'Paricatamole',
                },
                {
                    name: 'Ace® Power',
                    qty: '500mg',
                    type: 'Paricatamole',
                },
                {
                    name: 'Ace® Power',
                    qty: '500mg',
                    type: 'Paricatamole',
                },
                {
                    name: 'Ace® Power',
                    qty: '500mg',
                    type: 'Paricatamole',
                },
                {
                    name: 'Ace® Power',
                    qty: '500mg',
                    type: 'Paricatamole',
                },
                {
                    name: 'Ace® Power',
                    qty: '500mg',
                    type: 'Paricatamole',
                },
                {
                    name: 'Ace® Power',
                    qty: '500mg',
                    type: 'Paricatamole',
                },
                {
                    name: 'Ace® Power',
                    qty: '500mg',
                    type: 'Paricatamole',
                },
                {
                    name: 'Ace® Power',
                    qty: '500mg',
                    type: 'Paricatamole',
                },
                {
                    name: 'Ace® Power',
                    qty: '500mg',
                    type: 'Paricatamole',
                },
                {
                    name: 'Ace® Power',
                    qty: '500mg',
                    type: 'Paricatamole',
                },
                {
                    name: 'Ace® Power',
                    qty: '500mg',
                    type: 'Paricatamole',
                },
                {
                    name: 'Ace® Power',
                    qty: '500mg',
                    type: 'Paricatamole',
                },
                {
                    name: 'Ace® Power',
                    qty: '500mg',
                    type: 'Paricatamole',
                },
                {
                    name: 'Ace® Power',
                    qty: '500mg',
                    type: 'Paricatamole',
                },
                {
                    name: 'Ace® Power',
                    qty: '500mg',
                    type: 'Paricatamole',
                },
                {
                    name: 'Ace® Power',
                    qty: '500mg',
                    type: 'Paricatamole',
                },
            ]
        }

        return data
    }
}