export default class DemoPrintData {

    print_sdr_015_data() {
        let data = 
            {
                doc_apendix: [
                    {
                        apendix: "9.2, Invoice",
                        doc_no: "07-05.5-05-00 (Dist), Revision No. 00",
                        form_no: "07-5.5-05-02",
                    }
                ],
                invoice_header_data: [
                    {
                        customer_code: "DHK34105",
                        customer_name: "LABAID CARDIAC HOSPITAL",
                        address: "HOUSE-01, RAOD-04, DHANMONDI",
                        MIO_name: "SHAHIDUL ISLAM",
                        SR_name: "RAMJAN ALI",
                        invoice_no: "DHK081920086",
                        invoice_date: "30/09/2019",
                        depot: "Dhaka Depot",
                        t_code: "DHK341",
                        date: "29.09.2019",
                        order_no: "000380864-0601",
                    }
                ],
                table_data: [
                    {
                        sn: "1",
                        product_name: "Adarbi 40 Tablet",
                        pack_size: "20's",
                        batch_no: "111119",
                        mfg_date: "Jan'19",
                        eXP_date: "Dec.'20",
                        unit_price_TP_SP: "179.91",
                        unit_VAT: "  31.30",
                        unit_price_with_VAT: "211.21",
                        qty: "2",
                        bonus: "0",
                        total_VAT: "62.61",
                        total_TP_SP: "359.82"
                    },
                    {
                        sn: "1",
                        product_name: "Adarbi 40 Tablet",
                        pack_size: "20's",
                        batch_no: "111119",
                        mfg_date: "Jan'19",
                        eXP_date: "Dec.'20",
                        unit_price_TP_SP: "179.91",
                        unit_VAT: "  31.30",
                        unit_price_with_VAT: "211.21",
                        qty: "2",
                        bonus: "0",
                        total_VAT: "62.61",
                        total_TP_SP: "359.82"
                    },
                    {
                        sn: "1",
                        product_name: "Adarbi 40 Tablet",
                        pack_size: "20's",
                        batch_no: "111119",
                        mfg_date: "Jan'19",
                        eXP_date: "Dec.'20",
                        unit_price_TP_SP: "179.91",
                        unit_VAT: "  31.30",
                        unit_price_with_VAT: "211.21",
                        qty: "2",
                        bonus: "0",
                        total_VAT: "62.61",
                        total_TP_SP: "359.82"
                    },
                    {
                        sn: "1",
                        product_name: "Adarbi 40 Tablet",
                        pack_size: "20's",
                        batch_no: "111119",
                        mfg_date: "Jan'19",
                        eXP_date: "Dec.'20",
                        unit_price_TP_SP: "179.91",
                        unit_VAT: "  31.30",
                        unit_price_with_VAT: "211.21",
                        qty: "2",
                        bonus: "0",
                        total_VAT: "62.61",
                        total_TP_SP: "359.82"
                    },
                    {
                        sn: "1",
                        product_name: "Adarbi 40 Tablet",
                        pack_size: "20's",
                        batch_no: "111119",
                        mfg_date: "Jan'19",
                        eXP_date: "Dec.'20",
                        unit_price_TP_SP: "179.91",
                        unit_VAT: "  31.30",
                        unit_price_with_VAT: "211.21",
                        qty: "2",
                        bonus: "0",
                        total_VAT: "62.61",
                        total_TP_SP: "359.82"
                    },
                    {
                        sn: "1",
                        product_name: "Adarbi 40 Tablet",
                        pack_size: "20's",
                        batch_no: "111119",
                        mfg_date: "Jan'19",
                        eXP_date: "Dec.'20",
                        unit_price_TP_SP: "179.91",
                        unit_VAT: "  31.30",
                        unit_price_with_VAT: "211.21",
                        qty: "2",
                        bonus: "0",
                        total_VAT: "62.61",
                        total_TP_SP: "359.82"
                    },
                    {
                        sn: "1",
                        product_name: "Adarbi 40 Tablet",
                        pack_size: "20's",
                        batch_no: "111119",
                        mfg_date: "Jan'19",
                        eXP_date: "Dec.'20",
                        unit_price_TP_SP: "179.91",
                        unit_VAT: "  31.30",
                        unit_price_with_VAT: "211.21",
                        qty: "2",
                        bonus: "0",
                        total_VAT: "62.61",
                        total_TP_SP: "359.82"
                    },
                    {
                        sn: "1",
                        product_name: "Adarbi 40 Tablet",
                        pack_size: "20's",
                        batch_no: "111119",
                        mfg_date: "Jan'19",
                        eXP_date: "Dec.'20",
                        unit_price_TP_SP: "179.91",
                        unit_VAT: "  31.30",
                        unit_price_with_VAT: "211.21",
                        qty: "2",
                        bonus: "0",
                        total_VAT: "62.61",
                        total_TP_SP: "359.82"
                    },
                    {
                        sn: "1",
                        product_name: "Adarbi 40 Tablet",
                        pack_size: "20's",
                        batch_no: "111119",
                        mfg_date: "Jan'19",
                        eXP_date: "Dec.'20",
                        unit_price_TP_SP: "179.91",
                        unit_VAT: "  31.30",
                        unit_price_with_VAT: "211.21",
                        qty: "2",
                        bonus: "0",
                        total_VAT: "62.61",
                        total_TP_SP: "359.82"
                    },
                    {
                        sn: "1",
                        product_name: "Adarbi 40 Tablet",
                        pack_size: "20's",
                        batch_no: "111119",
                        mfg_date: "Jan'19",
                        eXP_date: "Dec.'20",
                        unit_price_TP_SP: "179.91",
                        unit_VAT: "  31.30",
                        unit_price_with_VAT: "211.21",
                        qty: "2",
                        bonus: "0",
                        total_VAT: "62.61",
                        total_TP_SP: "359.82"
                    },
                    {
                        sn: "1",
                        product_name: "Adarbi 40 Tablet",
                        pack_size: "20's",
                        batch_no: "111119",
                        mfg_date: "Jan'19",
                        eXP_date: "Dec.'20",
                        unit_price_TP_SP: "179.91",
                        unit_VAT: "  31.30",
                        unit_price_with_VAT: "211.21",
                        qty: "2",
                        bonus: "0",
                        total_VAT: "62.61",
                        total_TP_SP: "359.82"
                    },
                    {
                        sn: "1",
                        product_name: "Adarbi 40 Tablet",
                        pack_size: "20's",
                        batch_no: "111119",
                        mfg_date: "Jan'19",
                        eXP_date: "Dec.'20",
                        unit_price_TP_SP: "179.91",
                        unit_VAT: "  31.30",
                        unit_price_with_VAT: "211.21",
                        qty: "2",
                        bonus: "0",
                        total_VAT: "62.61",
                        total_TP_SP: "359.82"
                    },
                    {
                        sn: "1",
                        product_name: "Adarbi 40 Tablet",
                        pack_size: "20's",
                        batch_no: "111119",
                        mfg_date: "Jan'19",
                        eXP_date: "Dec.'20",
                        unit_price_TP_SP: "179.91",
                        unit_VAT: "  31.30",
                        unit_price_with_VAT: "211.21",
                        qty: "2",
                        bonus: "0",
                        total_VAT: "62.61",
                        total_TP_SP: "359.82"
                    },
                    {
                        sn: "1",
                        product_name: "Adarbi 40 Tablet",
                        pack_size: "20's",
                        batch_no: "111119",
                        mfg_date: "Jan'19",
                        eXP_date: "Dec.'20",
                        unit_price_TP_SP: "179.91",
                        unit_VAT: "  31.30",
                        unit_price_with_VAT: "211.21",
                        qty: "2",
                        bonus: "0",
                        total_VAT: "62.61",
                        total_TP_SP: "359.82"
                    },
                    {
                        sn: "1",
                        product_name: "Adarbi 40 Tablet",
                        pack_size: "20's",
                        batch_no: "111119",
                        mfg_date: "Jan'19",
                        eXP_date: "Dec.'20",
                        unit_price_TP_SP: "179.91",
                        unit_VAT: "  31.30",
                        unit_price_with_VAT: "211.21",
                        qty: "2",
                        bonus: "0",
                        total_VAT: "62.61",
                        total_TP_SP: "359.82"
                    },
                    {
                        sn: "1",
                        product_name: "Adarbi 40 Tablet",
                        pack_size: "20's",
                        batch_no: "111119",
                        mfg_date: "Jan'19",
                        eXP_date: "Dec.'20",
                        unit_price_TP_SP: "179.91",
                        unit_VAT: "  31.30",
                        unit_price_with_VAT: "211.21",
                        qty: "2",
                        bonus: "0",
                        total_VAT: "62.61",
                        total_TP_SP: "359.82"
                    },
                    {
                        sn: "1",
                        product_name: "Adarbi 40 Tablet",
                        pack_size: "20's",
                        batch_no: "111119",
                        mfg_date: "Jan'19",
                        eXP_date: "Dec.'20",
                        unit_price_TP_SP: "179.91",
                        unit_VAT: "  31.30",
                        unit_price_with_VAT: "211.21",
                        qty: "2",
                        bonus: "0",
                        total_VAT: "62.61",
                        total_TP_SP: "359.82"
                    },
                    {
                        sn: "1",
                        product_name: "Adarbi 40 Tablet",
                        pack_size: "20's",
                        batch_no: "111119",
                        mfg_date: "Jan'19",
                        eXP_date: "Dec.'20",
                        unit_price_TP_SP: "179.91",
                        unit_VAT: "  31.30",
                        unit_price_with_VAT: "211.21",
                        qty: "2",
                        bonus: "0",
                        total_VAT: "62.61",
                        total_TP_SP: "359.82"
                    },
                    {
                        sn: "1",
                        product_name: "Adarbi 40 Tablet",
                        pack_size: "20's",
                        batch_no: "111119",
                        mfg_date: "Jan'19",
                        eXP_date: "Dec.'20",
                        unit_price_TP_SP: "179.91",
                        unit_VAT: "  31.30",
                        unit_price_with_VAT: "211.21",
                        qty: "2",
                        bonus: "0",
                        total_VAT: "62.61",
                        total_TP_SP: "359.82"
                    },
                    {
                        sn: "1",
                        product_name: "Adarbi 40 Tablet",
                        pack_size: "20's",
                        batch_no: "111119",
                        mfg_date: "Jan'19",
                        eXP_date: "Dec.'20",
                        unit_price_TP_SP: "179.91",
                        unit_VAT: "  31.30",
                        unit_price_with_VAT: "211.21",
                        qty: "2",
                        bonus: "0",
                        total_VAT: "62.61",
                        total_TP_SP: "359.82"
                    },
                    {
                        sn: "1",
                        product_name: "Adarbi 40 Tablet",
                        pack_size: "20's",
                        batch_no: "111119",
                        mfg_date: "Jan'19",
                        eXP_date: "Dec.'20",
                        unit_price_TP_SP: "179.91",
                        unit_VAT: "  31.30",
                        unit_price_with_VAT: "211.21",
                        qty: "2",
                        bonus: "0",
                        total_VAT: "62.61",
                        total_TP_SP: "359.82"
                    }
                ]
            }

        return data
    }
    print_sdr_015_data_table() {
        let data = [
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                bonus: "0",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
        ]

        return data
    }

    print_sdr_017_data() {
        let data = [
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                dispatch_qty: "1",
                dispatch_bonus: "0",
                overall_return_return: "0",
                overall_return_bonus: "0",
                net_sales: "1",
                return_status_TP: "",
                return_status_VAT: "",
                net_sales_after_return_TP: "225.64",
                net_sales_after_return_VAT: "39.26",
                net_sales_after_return_Net_price: "264.90",
            },
        ]

        return data
    }

    print_sdr_018_data() {
        let data = [
            {
                sn: "1",
                product_name: "Adarbi 40 Tablet",
                pack_size: "20's",
                batch_no: "111119",
                mfg_date: "Jan'19",
                eXP_date: "Dec.'20",
                unit_price_TP_SP: "179.91",
                unit_VAT: "  31.30",
                unit_price_with_VAT: "211.21",
                qty: "2",
                total_VAT: "62.61",
                total_TP_SP: "359.82"
            },
        ]

        return data
    }

    print_sdr_023_data() {
        let data = [
            {
                invoice_no: "",
                date: "20's",
                cust_code: "111119",
                custoemrName: "Jan'19",
                address: "Dec.'20",
                invoice_amount: "179.91",
            },
            {
                invoice_no: "",
                date: "20's",
                cust_code: "111119",
                custoemrName: "Jan'19",
                address: "Dec.'20",
                invoice_amount: "179.91",
            },
            {
                invoice_no: "",
                date: "20's",
                cust_code: "111119",
                custoemrName: "Jan'19",
                address: "Dec.'20",
                invoice_amount: "179.91",
            },
            {
                invoice_no: "",
                date: "20's",
                cust_code: "111119",
                custoemrName: "Jan'19",
                address: "Dec.'20",
                invoice_amount: "179.91",
            },
            {
                invoice_no: "",
                date: "20's",
                cust_code: "111119",
                custoemrName: "Jan'19",
                address: "Dec.'20",
                invoice_amount: "179.91",
            },
            {
                invoice_no: "",
                date: "20's",
                cust_code: "111119",
                custoemrName: "Jan'19",
                address: "Dec.'20",
                invoice_amount: "179.91",
            },
        ]

        return data
    }

    print_sdr_024_data() {
        let data = [
            {
                invoice_no: "DHK062028680",
                date: "28/06/2020",
                chemist_name: "Chowdury Medical Hall",
                invoice_type: "Cash",
                collection_amount: "412.00",
            },
            {
                invoice_no: "DHK062028680",
                date: "28/06/2020",
                chemist_name: "Chowdury Medical Hall",
                invoice_type: "Cash",
                collection_amount: "412.00",
            },
            {
                invoice_no: "DHK062028680",
                date: "28/06/2020",
                chemist_name: "Chowdury Medical Hall",
                invoice_type: "Cash",
                collection_amount: "412.00",
            },
            {
                invoice_no: "DHK062028680",
                date: "28/06/2020",
                chemist_name: "Chowdury Medical Hall",
                invoice_type: "Cash",
                collection_amount: "412.00",
            },
            {
                invoice_no: "DHK062028680",
                date: "28/06/2020",
                chemist_name: "Chowdury Medical Hall",
                invoice_type: "Cash",
                collection_amount: "412.00",
            },
            {
                invoice_no: "DHK062028680",
                date: "28/06/2020",
                chemist_name: "Chowdury Medical Hall",
                invoice_type: "Cash",
                collection_amount: "412.00",
            },
            {
                invoice_no: "DHK062028680",
                date: "28/06/2020",
                chemist_name: "Chowdury Medical Hall",
                invoice_type: "Cash",
                collection_amount: "412.00",
            },
            {
                invoice_no: "DHK062028680",
                date: "28/06/2020",
                chemist_name: "Chowdury Medical Hall",
                invoice_type: "Cash",
                collection_amount: "412.00",
            },
            {
                invoice_no: "DHK062028680",
                date: "28/06/2020",
                chemist_name: "Chowdury Medical Hall",
                invoice_type: "Cash",
                collection_amount: "412.00",
            },
            {
                invoice_no: "DHK062028680",
                date: "28/06/2020",
                chemist_name: "Chowdury Medical Hall",
                invoice_type: "Cash",
                collection_amount: "412.00",
            },
            {
                invoice_no: "DHK062028680",
                date: "28/06/2020",
                chemist_name: "Chowdury Medical Hall",
                invoice_type: "Cash",
                collection_amount: "412.00",
            },
        ]

        return data
    }

    print_sdr_025_data() {
        let data = [
            {
                invoice_no: "1053629",
                dispatch_date: "28/06/2020",
                net_sale: "6,163.66",
                type: "Cash",
                prev_collection: "1,000.00",
                collection_amnt: "1,400.00",
                return_amnt: "-",
                balance_amnt: "3,763.66",
            },
            {
                invoice_no: "1053629",
                dispatch_date: "28/06/2020",
                net_sale: "6,163.66",
                type: "Cash",
                prev_collection: "1,000.00",
                collection_amnt: "1,400.00",
                return_amnt: "-",
                balance_amnt: "3,763.66",
            },
            {
                invoice_no: "1053629",
                dispatch_date: "28/06/2020",
                net_sale: "6,163.66",
                type: "Cash",
                prev_collection: "1,000.00",
                collection_amnt: "1,400.00",
                return_amnt: "-",
                balance_amnt: "3,763.66",
            },
            {
                invoice_no: "1053629",
                dispatch_date: "28/06/2020",
                net_sale: "6,163.66",
                type: "Cash",
                prev_collection: "1,000.00",
                collection_amnt: "1,400.00",
                return_amnt: "-",
                balance_amnt: "3,763.66",
            },
            {
                invoice_no: "1053629",
                dispatch_date: "28/06/2020",
                net_sale: "6,163.66",
                type: "Cash",
                prev_collection: "1,000.00",
                collection_amnt: "1,400.00",
                return_amnt: "-",
                balance_amnt: "3,763.66",
            },
            {
                invoice_no: "1053629",
                dispatch_date: "28/06/2020",
                net_sale: "6,163.66",
                type: "Cash",
                prev_collection: "1,000.00",
                collection_amnt: "1,400.00",
                return_amnt: "-",
                balance_amnt: "3,763.66",
            },
            {
                invoice_no: "1053629",
                dispatch_date: "28/06/2020",
                net_sale: "6,163.66",
                type: "Cash",
                prev_collection: "1,000.00",
                collection_amnt: "1,400.00",
                return_amnt: "-",
                balance_amnt: "3,763.66",
            },
            {
                invoice_no: "1053629",
                dispatch_date: "28/06/2020",
                net_sale: "6,163.66",
                type: "Cash",
                prev_collection: "1,000.00",
                collection_amnt: "1,400.00",
                return_amnt: "-",
                balance_amnt: "3,763.66",
            },
            {
                invoice_no: "1053629",
                dispatch_date: "28/06/2020",
                net_sale: "6,163.66",
                type: "Cash",
                prev_collection: "1,000.00",
                collection_amnt: "1,400.00",
                return_amnt: "-",
                balance_amnt: "3,763.66",
            },
            {
                invoice_no: "1053629",
                dispatch_date: "28/06/2020",
                net_sale: "6,163.66",
                type: "Cash",
                prev_collection: "1,000.00",
                collection_amnt: "1,400.00",
                return_amnt: "-",
                balance_amnt: "3,763.66",
            },
        ]

        return data
    }
}